apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ibm-mq-promote-dev-stage
  annotations:
    app.openshift.io/runtime: test
spec:
  params:
    - name: git-url
      description: The url for the git repository
    - name: git-revision
      description: git branch for the test app
      default: master
    - name: src-environment
      description: environment
      default: dev
    - name: dest-environment
      description: environment
      default: staging
    - name: app-path
      description: Path in gitops repo
      default: mq/environments
    - name: git-pr
      description: Enable the pipeline to do a PR for the gitops repo
      default: "true"
    - name: test-file
      description: Path of the postman collection
      default: "postman/mq-spring-app.postman_collection.json"
  tasks:
    - name: dev-instance-tests
      taskRef:
        name: ibm-functional-test
      params:
        - name: git-url
          value: "$(params.git-url)"
        - name: src-environment
          value: "$(params.src-environment)"
        - name: test-file
          value: "$(params.test-file)"
    - name: app-name
      taskRef:
        name: ibm-app-name
      runAfter:
        - dev-instance-tests
      params:
        - name: git-url
          value: "$(params.git-url)"
    - name: gitops
      taskRef:
        name: ibm-gitops-promotion
      runAfter:
        - app-name
      params:
        - name: app-name
          value: "$(tasks.app-name.results.app-name)"
        - name: src-environment
          value: "$(params.src-environment)"
        - name: dest-environment
          value: "$(params.dest-environment)"
        - name: app-path
          value: "$(params.app-path)"
        - name: git-pr
          value: "$(params.git-pr)"
