kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-apic-config-pipeline
  namespace: tools
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - 'route.openshift.io'
      - 'apiconnect.ibm.com'
      - 'management.apiconnect.ibm.com'
      - ''
    resources:
      - routes
      - secrets
      - apiconnectclusters
      - managementclusters