apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: mq-infra-post-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - name: mq-infra-post-dev
      template:
        ref: mq-infra-post-dev
