kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-pipeline-sa
  namespace: prod
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-pipeline-sa
