kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-pipeline-sa
rules:
  - verbs:
      - '*'
    apiGroups:
      - 'bitnami.com'
    resources:
      - sealedsecrets
  - verbs:
      - '*'
    apiGroups:
      - tekton.dev
    resources:
      - pipelines
      - pipelineruns
      - tasks
      - taskruns
      - pipelineresources
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - services
      - pods/log
  - verbs:
      - '*'
    apiGroups:
      - 'route.openshift.io'
    resources:
      - routes
  - verbs:
      - '*'
    apiGroups:
      - 'mq.ibm.com'
    resources:
      - queuemanagers
  - verbs:
      - '*'
    apiGroups:
      - 'batch'
    resources:
      - jobs
