apiVersion: v1
kind: Service
metadata:
  name: soapserver-nonsecure
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: soapserver-nonsecure
  sessionAffinity: None
  type: ClusterIP
