apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-passwords
  namespace: tools
spec:
  encryptedData:
    CLIENT_SSL_KEY_STORE_PASSWORD: AgADnDD81F+Y6YgD+8EFteNuSkj3wlzHsWnDX6Zm+zY0BxotCJ3hk2Mj9vGcBxcrIG/viQvIpKkvai9ORcZb+HXkGlA1o2AewKxD4ZOsQJOBzs8hJ/Zs/RftTDDf9XpldTkZE1KcevVcZJLks3GAZlYgh7jsijzyPWBlqB4nLwAhT+VOpzVNTT8xganceFa2L1DlOMixQ2fYWHL8dxieSVMXvjQI0xJer5R9MwPVLOIqbzeGskSDWMPbgBYHZPzkFhDvlGsCwi2BOr/bJ6vLDNGPaFfQ4Hst97jkoqn9Q7Nzjdxmr0Z1yq8sEQwZvJMxmggT0Vl96XNNfCFYmCTqmRvkcfv7oq7Nj5h0IKOXTdMI2cJxQwkwPajt0646+58QX0b9SPJaRgVfUwuNnn2tTmOBAerbtDhA/JoJBl/FUqGPhj3X4bpe+yxvoMhnau9tMgMBJqtBPe90IYmQkKZbeM9p7UTmN5tDWAuyDof1f2NaZulYnAnxz/KvKocGqCOYJThH+2p+Dbnf2/liCS6t85Z5SUW10rcT+lHV5gus6gQNy/ucVsnNaMQboRPnUBQl7yaASBknTvB9ixXwLG2XeeeWu/t7MdkYmv1baJrRU7JIZRCW5Q60uHT6aH422/47pBgY3NUw122lryopzgp5Qlb4cq3y3IsMyJmoFHT3zGNP5phzhjeXAISWJ5lS4wvtklFA2/FtIq+blg==
    CLIENT_SSL_TRUST_STORE_PASSWORD: AgBn+AGZplcZTg5Wec+J09VqnIEH8QJqAAOQIBb66n+lO4x1autyFY1eFwULqN7Kkx13ve41XeXfc0FTpbXn8HFz03ZdwP9cqnQybKVdqKoq1ozNyEcopcpWdTEEYqznZ/zXK+thyi+q1AmW6AYdXGkv2LrwLrUDFglam7zwueH5CQ6wQhwOTA6yqdxlMeEqwCbo/TgtR8hamoklCmN9aqUEQ70ZDUWzHkOShnR0tv+WI9hxCXImLwqEiOd8yFmYq9bnRkRr/bqOjd0YN70hYEBZjtwc85t8Y/14v3tZvFgx6TKrgDUA4zAYxhuJ4W+r3+VWfArt9PALZxFNSSk8w9oyPgvjg7uVSKknEzfqv9e/A1Fk6TqqKkkc7Njea0PDl6DLczImzGrE3S/1X53rUQCco9ADhydmq9MU9jHnTKr/Pr8BDs4pQjwk94qOBiQhoDlj1JZJmjGYBVdPY2tH01ZL/EopbeqXAUdzi5uRERaLTtFW3jce6Ombi3m2q1FBG75zUWUctjFF3I2+Bk3ZThdzEiUg16OvYi0ESRxi0DArksycDAMc/PKk6E62gP5CxQsduTPZbABamf3mCMLv+8UtlS8yYVcqgk+cnaeEXh12SGT2VmFLc4Zv2kCbgkuDLkmFnvjRe/JlV9xL4c+giXd0fRC1d8RgEvkhlIQTJTUwpNmjR0C/PlNI9GIK/4Y6fF+2VhjdsnFniw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-passwords
      namespace: tools
    type: Opaque

