apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ace-config
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: ace-config
      template:
        ref: ace-config
