apiVersion: apps/v1
kind: Deployment
metadata:
  name: soapserver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: soapserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: soapserver
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: secure
        - name: CLIENT_SSL_KEY_STORE
          value: /certs/ibm-soap-server.jks
        - name: CLIENT_SSL_TRUST_STORE
          value: /certs/ibm-ca.jks
        envFrom:
        - secretRef:
            name: ibm-passwords
        image: quay.io/hollisc/soapserver:v1
        imagePullPolicy: Always
        name: soapserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /certs
          name: certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: ibm-jks
