apiVersion: apps/v1
kind: Deployment
metadata:
  name: soapserver-nonsecure
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: soapserver-nonsecure
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: soapserver-nonsecure
    spec:
      containers:
      - image: quay.io/hollisc/soapserver:v1
        imagePullPolicy: Always
        name: soapserver-nonsecure
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30