apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "255"
  labels:
    gitops.tier.group: cntk
spec:
  selfSigned: {}
