---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cp4a-shared-log-pvc
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 21.0.1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cp4a-file-retain-gold-gid
  resources:
    requests:
      storage: 100Gi
