---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: operator-shared-pvc
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 21.0.1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cp4a-file-retain-bronze-gid
  resources:
    requests:
      storage: 1Gi
