apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: REPLACE
    ARTIFACTORY_PASSWORD: REPLACE
    ARTIFACTORY_URL: REPLACE
    ARTIFACTORY_USER: REPLACE
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: artifactory-access
      namespace: ci
    type: Opaque

