apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgC/IDRuifBGjSqgHLqHZGxM5hujOpYRTZPtDVcU4p3iG4hvXSOOGl5UISvNjagrUfBRq9u+olJXfMB9jEXt6mHvwLlbjpLsACuZUZDM35M+BSs3MLpuv7+mJDzcfHPc6B1gOoL+10UqsFjO+AU4c/eGmGYpX9S8A7M979gaiXh2IqxFgvOIe7Nb3il0HtmgqkYI7c0znrNtw20f1YdlxJiY0Uisuk9PdpJOcZJ3OVa4iTgwJFYTJgLu/hqMmmeW028xV67TIM8cN8U4rCjiHico6SUviIsUh9V8JVkiFP3m6tCzdIy8/w1pn0F3i/Dw5ZzaOLdkpg6I2Ni0qlGnKBhNwivaI2BoKQvvcL594TZY7L+6z//A8ifkbMHv9Q79VlXZo7uAygnOR6hn/NBNC8Pvr4s8wDXMVfL0di7plngRl8vCagr2vekaiKS1XKM8IP3SMYXZ2d/PsVWRfq5gu4rRREd+5CPb/bLJZatI2m/ySWRKznKC+4GHOP/7M0QRRgpntdjPS5Kuh+0cUOQUkIFVoN89srbcL4gkCuTS6J+eC2MDUsl9reysn8Twz/2RdzAMct3uaq/IBsxdbROiVraRfsb5/pjbB0N29R6hlmJshqPfVIeeBPIQ5Z08WGAU5l9zdEEsghe5LWZGEezvvvw16VR9AnK1V1lBxEtqwy0aYKbjdjW2UQZB8lOLJtceATvj+EqY4iP0/YGoYFL2er5G47rA2y1hIj57HPLqLi77Rd3+6M4AXRx4gbcwty6cR3aPBdZI/259So1P8NIoMuxMkzEmy8PyxXonYRhL5Ec5uOJgAk0AFlvo4w56YGh6nlXQgYRzhr7Wu1ekBzcYhC2/or/VE9e+5GfXF3rwtz9KVfEtnPX3I2Rc3xqg3J1clcY7pqQFh+9t6x5vWaFcMFl6DgNttx5KQUy6Kjy/87A2vw==
    IBM_ENTITLED_REGISTRY_USER: AgByioOcuyg/Je9GIbjBQ6eSuj57my+1XR6G6khYXWA8WkMbbnhsFQE6w3G3+9J6jmd/dGchGSKyN+9HvZ3b8hFeu2TUe/Y10FKE8VP0oqwJuT07l+MxarKUEqGts6LoG+qfOg9fNiETLlmGDjBKbkDzXLaMellUOIGtuwPSuanxtoB3jPfk6X9G8+rPLcqgif1f6FWNTlsWUS3umOOl/rXuyLZtdGyYXEJcVBPzePTzp/jtnQ74XkbhQZKVULX31QqmU3dMyA4a0ODMPJP8b8ljQlnoZK+OIO3e25X3fSE5nnvb1IN4RkjYZNMni6f0KSop/uJYGm/5I3S/5AbCtWlSauCwCzfRSqC9IuGI5j1gsz+ZQFvKLrNw+xSWO2dCAY2S3hLHIGGY0Y/1m0KXIOyK4MiQ0iAtPeZF5H5JF4YdzvQib72PjLsMHOePNd4f6nOFHcW1oshvLet3qCRkMm/fxSIg+FKMI8trTPPbjAGtwItxLwDIvEz8bzx5Gi0bISniVYdZL/6X3a8+9UOmmGULDNI1YcHNgFrmkgD/W36MZAEilbjee4LRLnOAoVTnV8P98P0Hb0g0i2Uyy2wH0x41dEV5EaghW8uk2KH0+MwdKty6viqMm44/IC2ClL78cfn2VfzKf4mpQlDcN82U3Bp3sh2Muzo98SO3t89aT4OYUFTQZo35BKZLSIpASRIZvWaobA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

