apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-analytics-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: apic/environments/multi-cluster/instances/template-gateway-analytics-instance
    repoURL: https://github.com/tutorial-org-123/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
