kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cphtestp-sa
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
