kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cphtestp-sa
  namespace: staging
subjects:
  - kind: ServiceAccount
    name: default
    namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cphtestp-sa
